### ISSUE TITLE
Antenatal Care Visit program duplicate

### ISSUE THREAD

**Issue by Birkbjo** [dhis2/dhis2-demo-db#15]
While trying to save 'Antenatal Care Program' the server responds with 'internal server error: 500'.

Server logs: 

`
 core_1     | * WARN  2019-07-31 13:24:55,817 SQL Error: 0, SQLState: 23505 (SqlExceptionHelper.java [http-nio-8080-exec-3])
core_1     | * ERROR 2019-07-31 13:24:55,818 ERROR: duplicate key value violates unique constraint "programstage_name_key"
core_1     |   Detail: Key (name)=(Antenatal care visit) already exists. (SqlExceptionHelper.java [http-nio-8080-exec-3])
`

It seems like there's a dangling program-stage tuple that references the program.

If we rename the program it's saved successfully.

**Comment by Bekkalizer** [comment]
Yeah, this is being fixed in [DHIS2-7308](https://jira.dhis2.org/browse/DHIS2-7308)
